### ISSUE TITLE
"fixed" type not working

### ISSUE THREAD

**Issue by quinarnold** [rbystrit/avro_gen#12]
I'm getting the following error for a fixed type field:

 ****************************************************************************************************
Exception in FieldsCollector while processing schema: mxe
 ****************************************************************************************************
Traceback (most recent call last):
  File "/home/qarnold/.conda/envs/datahub2/bin/pyavrogen.py", line 64, in <module>
    AVRO_GENERATOR.process(ARGS.modules)
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/avro_preprocessor/preprocessor.py", line 99, in process
    self._do_process(self.modules)
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/avro_preprocessor/preprocessor.py", line 113, in _do_process
    raise exc
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/avro_preprocessor/preprocessor.py", line 108, in _do_process
    module.process()
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/pyavro_gen/modules/fields_collector.py", line 43, in process
    self.traverse_schema(self.fill_fields_of_node, schema)
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/avro_preprocessor/preprocessor_module.py", line 81, in traverse_schema
    self.do_traverse_schema(func, node)
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/avro_preprocessor/preprocessor_module.py", line 106, in do_traverse_schema
    while self.do_traverse_schema(func, node[key]):
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/avro_preprocessor/preprocessor_module.py", line 106, in do_traverse_schema
    while self.do_traverse_schema(func, node[key]):
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/avro_preprocessor/preprocessor_module.py", line 106, in do_traverse_schema
    while self.do_traverse_schema(func, node[key]):
  [Previous line repeated 1 more time]
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/avro_preprocessor/preprocessor_module.py", line 96, in do_traverse_schema
    res = func(node)
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/pyavro_gen/modules/fields_collector.py", line 57, in fill_fields_of_node
    self.fill_fields_of_standard_record(node)
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/pyavro_gen/modules/fields_collector.py", line 143, in fill_fields_of_standard_record
    field_type = self.get_class_writer_for_node(avro_type)
  File "/home/qarnold/.conda/envs/datahub2/lib/python3.8/site-packages/pyavro_gen/modules/fields_collector.py", line 266, in get_class_writer_for_node
    raise TypeError(f'Type unsupported: {str(avro_type)}')
TypeError: Type unsupported: OrderedDict([('type', 'fixed'), ('name', 'UUID'), ('size', 16)])

**Comment by quinarnold** [comment]
Sorry, this was meant for pyavro-gen
